# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26c63b85100b1b4a00ce60acfc2c94504113f24ebf826428a066f5ea1438f1d839e5fc22e0116cc6b331b729c3b899bb26935c2197e5ebba1d6a587af0e3e1ba

test:
  secret_key_base: 0fdbe17ca386ff0fa4eedf8635558ce95b7c19ede5e6935f8bab6fa52adec62a05d503eca9b830dfae32e2cbe9991d1aec58df88ba13539d1c5dc469c75a0801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
